fixed trap exit in zshrc by adding HUP, which is needed on mac when closing terminal manually (fuckn macos)

diff --git a/1 b/1
--- a/1
+++ b/1
@@ -25,18 +25,20 @@ elif [[ -f $_plugins_zsh ]]; then
     source $_plugins_zsh
 fi 
 
+
+
+
+
 #NOTE: WIP: idea is to persist 'fzd file' cache not per shell session (i.e. each pid)
 #but rather across all interactive shell session .. currently using marker files in /tmp/fzd_sessions/
 #Need to change fzd defintion to use marker files existence
 
- fzd_shells_init
- on_exit() {
-   fzd_shells_cleanup
-   # echo 'trap exit ran'
-   # echo "cleanup fired for $$" >> /tmp/cleanup.log
+
+ fzd.shells.init
+ do_exit_cleanup() {
+   fzd.shells.cleanup
+   # fzd.shells.cleanup
+   # fzd.cleanup
  }
 
- trap on_exit EXIT HUP 
- #subtle bug all along: HUP is needed on mac when terminal window closes (SIGHUP sent)
- #explains why without it and running 'time zsh -ic exit' things would work still, 
- #but not when closing and re-opening terminal window!
+ trap do_exit_cleanup EXIT
